name: 🚩 Push to Azure Container Registry
on:
  workflow_dispatch:
env:
  IMAGE_NAME: automation
jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    outputs:
      password1: ${{ steps.create_token.outputs.password1 }}
      password2: ${{ steps.create_token.outputs.password2 }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: 'Login to Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZ_USERNAME }}
          password: ${{ secrets.AZ_PASSWORD }}

      - name: 'Build and push Docker image to Azure Container Registry'
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:${{ github.sha }}
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$IMAGE_NAME:${{ github.sha }}

      # - name: 'Create ACR Token'
      #   id: create_token
      #   run: |
      #     ACR_TOKEN_JSON=$(az acr token create --name $IMAGE_NAME-token --registry ${{ secrets.ACR_REGISTRY_NAME }} \
      #     --repository $IMAGE_NAME content/read --output json)
      #     PASSWORD1=$(echo $ACR_TOKEN_JSON | jq '.credentials.passwords[0].value')
      #     PASSWORD2=$(echo $ACR_TOKEN_JSON | jq '.credentials.passwords[1].value')
      #     echo "password1=$PASSWORD1" >> $GITHUB_OUTPUT
      #     echo "password2=$PASSWORD2" >> $GITHUB_OUTPUT

      # - name: 'Saving passwords in a Key Vault'
      #   run: |
      #     az keyvault secret set --vault-name ${{ secrets.KEY_VAULT_NAME }} --name "password1" --value ${{ steps.create_token.outputs.password1 }}
      #     az keyvault secret set --vault-name ${{ secrets.KEY_VAULT_NAME }} --name "password2" --value ${{ steps.create_token.outputs.password2 }}